### ISSUE TITLE
No Description in Product Schema

### ISSUE THREAD

**Issue by gputignano** [adampmoss/CreareSEO#151]
I get warning in Schema validation of my site because description is blank in product Schema description field.
You can check here [https://search.google.com/structured-data/testing-tool/u/0/?hl=it#url=https%3A%2F%2Fwww.lacompagniadelcavatappi.com%2Foro-bianco-crema-di-mandorle-fiasconaro.html](url).
I searched in open and closed issue but I can't find this issue.

**Comment by sprankhub** [comment]
We do output a description, which is based on the attribute `short_description`:

https://github.com/adampmoss/CreareSEO/blob/2051d687c4c86ad7d9efe57638318119e360a33e/app/design/frontend/base/default/template/creareseo/product/schema.phtml#L13

I guess you have no value for `short_description` defined. You could copy the template to your template and change `short_description` to `description`. Although you should probably shorten it somehow, because I guess the schema.org description may not be too long.
